version: '3'
services:
  database:
    image: postgres 
    env_file:
      - database.env
    ports: 
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ 

  web:
    build : 
      context: .
      dockerfile:  Dockerfile
      args: 
        file_app: app.py 
    environment:
      DATABASE_URL : postgresql+psycopg2://test:password@database/metron_database
      APP_SETTINGS : "config.TestingConfig"
      PYTHONPATH : /app
    ports:
        - "8000:5000"
    depends_on: 
        - database
    volumes: 
      - ./:/app
volumes:
  database-data: 

