version: '3'
services:
  database:
    image: postgres # use latest official postgres version
    env_file:
      - database.env
    ports: 
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  web:
    build : 
      context: .
      dockerfile:  Dockerfile
    environment:
      DATABASE_URL : postgresql+psycopg2://test:password@database/metron_database

    ports:
        - "8000:5000"
    depends_on: 
        - database
volumes:
  database-data: # named volumes can be managed easier using docker-compose

