[tool.poetry]
name = "metron"
version = "0.1.0"
description = ""
authors = ["Your Name <cbeltran@umanis.com>"]

keywords = ["Poetry", "Metron", "Flask"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "*"
flask-SQLalchemy = "*"
pylint-flask = "*"
pylint_flask_sqlalchemy = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run = "wsgi:main"